### ISSUE TITLE
uses.tech points to your uses page with a / on the end.

### ISSUE THREAD

**Issue by tvbeek** [mijndert/website#8]
Hello Mijndert,

I found a small issue that a wanted to bring to your attention:

https://uses.tech/ points to https://mijndertstuij.nl/uses/ (with the slash on the end) but that result in a 404.

I think you can update the the url for uses.tech to be without the slash and/or resolve the page with slash.

**Comment by mijndert** [comment]
Thanks @tvbeek, fixed now.
